// Single source of truth for asset fields — consumed by the bulk upload route,
// the individual asset routes, and the frontend form.
//
// type values:
//   'text'        free-form string
//   'date'        DD/MM/YYYY or YYYY-MM-DD
//   'numeric'     decimal, must be >= 0
//   'integer'     whole number
//   'year'        4-digit year string, e.g. '2025'
//   'enum'        one of the fixed `values` array
//   'plant'       typed code resolved to plant_id via plants table
//   'department'  typed name/code resolved to dept_id via departments table
//
// master: asset_masters type string to validate against, or null

const ASSET_FIELD_SPEC = [
  {
    db:       'asset_code',
    col:      'Asset Code',
    label:    'Asset Code',
    required: true,
    type:     'text',
    master:   null,
    aliases:  ['asset code', 'asset_code', 'assetcode'],
  },
  {
    db:       'sub_sequence',
    col:      'Sub Asset Number',
    label:    'Sub Asset Number',
    required: true,
    type:     'integer',
    master:   null,
    aliases:  ['sub asset number', 'sub_asset_number', 'sub asset no', 'subasset'],
  },
  {
    db:       'date_of_purchase',
    col:      'Capitalized On',
    label:    'Capitalized On',
    required: true,
    type:     'date',
    master:   null,
    aliases:  ['capitalized on', 'date of purchase', 'purchase date', 'capitalized_on'],
  },
  {
    db:       'name',
    col:      'Asset Description',
    label:    'Asset Description',
    required: true,
    type:     'text',
    master:   null,
    aliases:  ['asset description', 'asset_description', 'asset name', 'name', 'description'],
  },
  {
    db:       'acquisition_value',
    col:      'Acquisition Value',
    label:    'Acquisition Value',
    required: true,
    type:     'numeric',
    master:   null,
    aliases:  ['acquisition value', 'acquisition_value', 'value', 'amount'],
  },
  {
    db:       'company_code',
    col:      'Company Code',
    label:    'Company Code',
    required: true,
    type:     'text',
    master:   'company_code',
    aliases:  ['company code', 'company_code', 'companycode'],
  },
  {
    db:       'plant_id',
    col:      'Business Area Code',
    label:    'Business Area Code',
    required: true,
    type:     'plant',
    master:   null,
    aliases:  ['business area code', 'business area', 'business_area', 'plant code', 'plantcode'],
  },
  {
    db:       'asset_class',
    col:      'Asset Class',
    label:    'Asset Class',
    required: true,
    type:     'text',
    master:   'asset_class',
    aliases:  ['asset class', 'asset_class', 'asset class description'],
  },
  {
    db:       'cost_center',
    col:      'Cost Center',
    label:    'Cost Center',
    required: true,
    type:     'text',
    master:   'cost_center',
    aliases:  ['cost center', 'cost_center', 'costcenter'],
  },
  {
    db:       'serial_number',
    col:      'Serial Number',
    label:    'Serial Number',
    required: false,
    type:     'text',
    master:   null,
    aliases:  ['serial number', 'serial_number', 'serial', 'sn'],
  },
  {
    db:       'reference_invoice_no',
    col:      'Reference / Invoice No',
    label:    'Reference / Invoice No',
    required: true,
    type:     'text',
    master:   null,
    aliases:  ['reference / invoice no', 'reference/invoice no', 'reference invoice no', 'invoice no', 'invoice number', 'reference_invoice_no'],
  },
  {
    db:       'supplier_name',
    col:      'Supplier Name',
    label:    'Supplier Name',
    required: true,
    type:     'text',
    master:   null,
    aliases:  ['supplier name', 'supplier_name', 'supplier', 'vendor'],
  },
  {
    db:       'make',
    col:      'Manufacturer of Asset',
    label:    'Manufacturer of Asset',
    required: true,
    type:     'text',
    master:   null,
    aliases:  ['manufacturer of asset', 'make', 'brand', 'manufacturer'],
  },
  {
    db:       'fiscal_year',
    col:      'Fiscal Year',
    label:    'Fiscal Year',
    required: true,
    type:     'year',
    master:   null,
    aliases:  ['fiscal year', 'fiscal_year', 'year'],
  },
  {
    db:       'category',
    col:      'Category',
    label:    'Category',
    required: true,
    type:     'text',
    master:   'category',
    aliases:  ['category'],
  },
  {
    db:       'dept_id',
    col:      'Department',
    label:    'Department',
    required: true,
    type:     'department',
    master:   null,
    aliases:  ['department', 'dept'],
  },
  {
    db:       'assigned_employee',
    col:      'Assigned Employee',
    label:    'Assigned Employee',
    required: true,
    type:     'text',
    master:   null,
    aliases:  ['assigned employee', 'assigned_employee', 'employee'],
  },
  {
    db:       'status',
    col:      'Status',
    label:    'Status',
    required: true,
    type:     'enum',
    values:   ['Active', 'Inactive'],
    master:   null,
    aliases:  ['status'],
  },
  {
    db:       'asset_status',
    col:      'Asset Status',
    label:    'Asset Status',
    required: true,
    type:     'text',
    master:   'asset_status',
    aliases:  ['asset status', 'asset_status'],
  },
  {
    db:       'warranty_date',
    col:      'Warranty Date',
    label:    'Warranty Date',
    required: false,
    type:     'date',
    master:   null,
    aliases:  ['warranty date', 'warranty_date'],
  },
  {
    db:       'notes',
    col:      'Note',
    label:    'Note',
    required: false,
    type:     'text',
    master:   null,
    aliases:  ['note', 'notes', 'remarks'],
  },
]

module.exports = ASSET_FIELD_SPEC
